--- #YAML:1.0
name: Posy-Plugin-Canonical
version: 0.51
author:
  - Kathryn Andersen
abstract: Posy plugin to force redirect to canonical URL.
license: bsd
requires:
  Posy: 0.9
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::Canonical:
    file: lib/Posy/Plugin/Canonical.pm
    version: 0.51
generated_by: Module::Build version 0.2607
